### ISSUE TITLE
Development startup

### ISSUE THREAD

**Issue by alexnaldo** [pjchavarria/aozora-ios#163]
Hi,

After many workaround I ready to code at Aozora sources, but my ParseDB doesn't have any data, so will be great if @pjchavarria publish any initial data. Without it is very hard help your development. For many thinks the App required data already saved.

**Comment by pjchavarria** [comment]
Hi @alexnaldo thanks for the help offer, unfortunately we'll have to make this repository private again for internal reasons. Again, thanks for trying to contribute!
